// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*Resp, error)
	Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginResp, error)
	Logout(ctx context.Context, in *LogoutReq, opts ...client.CallOption) (*Resp, error)
	GetLevel(ctx context.Context, in *GetLevelReq, opts ...client.CallOption) (*Resp, error)
	GetUserByPhone(ctx context.Context, in *GetUserByPhoneReq, opts ...client.CallOption) (*GetUserByPhoneResp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.service.user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*Resp, error) {
	req := c.c.NewRequest(c.name, "UserService.Register", in)
	out := new(Resp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginResp, error) {
	req := c.c.NewRequest(c.name, "UserService.Login", in)
	out := new(LoginResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Logout(ctx context.Context, in *LogoutReq, opts ...client.CallOption) (*Resp, error) {
	req := c.c.NewRequest(c.name, "UserService.Logout", in)
	out := new(Resp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetLevel(ctx context.Context, in *GetLevelReq, opts ...client.CallOption) (*Resp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetLevel", in)
	out := new(Resp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserByPhone(ctx context.Context, in *GetUserByPhoneReq, opts ...client.CallOption) (*GetUserByPhoneResp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserByPhone", in)
	out := new(GetUserByPhoneResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Register(context.Context, *RegisterReq, *Resp) error
	Login(context.Context, *LoginReq, *LoginResp) error
	Logout(context.Context, *LogoutReq, *Resp) error
	GetLevel(context.Context, *GetLevelReq, *Resp) error
	GetUserByPhone(context.Context, *GetUserByPhoneReq, *GetUserByPhoneResp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		Register(ctx context.Context, in *RegisterReq, out *Resp) error
		Login(ctx context.Context, in *LoginReq, out *LoginResp) error
		Logout(ctx context.Context, in *LogoutReq, out *Resp) error
		GetLevel(ctx context.Context, in *GetLevelReq, out *Resp) error
		GetUserByPhone(ctx context.Context, in *GetUserByPhoneReq, out *GetUserByPhoneResp) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Register(ctx context.Context, in *RegisterReq, out *Resp) error {
	return h.UserServiceHandler.Register(ctx, in, out)
}

func (h *userServiceHandler) Login(ctx context.Context, in *LoginReq, out *LoginResp) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}

func (h *userServiceHandler) Logout(ctx context.Context, in *LogoutReq, out *Resp) error {
	return h.UserServiceHandler.Logout(ctx, in, out)
}

func (h *userServiceHandler) GetLevel(ctx context.Context, in *GetLevelReq, out *Resp) error {
	return h.UserServiceHandler.GetLevel(ctx, in, out)
}

func (h *userServiceHandler) GetUserByPhone(ctx context.Context, in *GetUserByPhoneReq, out *GetUserByPhoneResp) error {
	return h.UserServiceHandler.GetUserByPhone(ctx, in, out)
}
