// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: comment.proto

package go_micro_service_comment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CommentService service

type CommentService interface {
	GetComments(ctx context.Context, in *GetCommentsReq, opts ...client.CallOption) (*GetCommentsResp, error)
	AddComment(ctx context.Context, in *AddCommentReq, opts ...client.CallOption) (*Resp, error)
}

type commentService struct {
	c    client.Client
	name string
}

func NewCommentService(name string, c client.Client) CommentService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.service.comment"
	}
	return &commentService{
		c:    c,
		name: name,
	}
}

func (c *commentService) GetComments(ctx context.Context, in *GetCommentsReq, opts ...client.CallOption) (*GetCommentsResp, error) {
	req := c.c.NewRequest(c.name, "CommentService.GetComments", in)
	out := new(GetCommentsResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentService) AddComment(ctx context.Context, in *AddCommentReq, opts ...client.CallOption) (*Resp, error) {
	req := c.c.NewRequest(c.name, "CommentService.AddComment", in)
	out := new(Resp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CommentService service

type CommentServiceHandler interface {
	GetComments(context.Context, *GetCommentsReq, *GetCommentsResp) error
	AddComment(context.Context, *AddCommentReq, *Resp) error
}

func RegisterCommentServiceHandler(s server.Server, hdlr CommentServiceHandler, opts ...server.HandlerOption) error {
	type commentService interface {
		GetComments(ctx context.Context, in *GetCommentsReq, out *GetCommentsResp) error
		AddComment(ctx context.Context, in *AddCommentReq, out *Resp) error
	}
	type CommentService struct {
		commentService
	}
	h := &commentServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CommentService{h}, opts...))
}

type commentServiceHandler struct {
	CommentServiceHandler
}

func (h *commentServiceHandler) GetComments(ctx context.Context, in *GetCommentsReq, out *GetCommentsResp) error {
	return h.CommentServiceHandler.GetComments(ctx, in, out)
}

func (h *commentServiceHandler) AddComment(ctx context.Context, in *AddCommentReq, out *Resp) error {
	return h.CommentServiceHandler.AddComment(ctx, in, out)
}
